version: '3.1'
networks:
  dev_network:

services:
  db:
    build: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    container_name: db_ads
    networks:
      dev_network:
        aliases:
          - db-main